services:
  app:
    build: .
    container_name: santo-ambrosius-app
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - media_data:/app/media
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      NODE_ENV: production

  mongo:
    image: mongo:latest
    container_name: santo-ambrosius-mongo
    ports:
      - '127.0.0.1:27017:27017'  # Only accessible from localhost
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command:
      - --storageEngine=wiredTiger
      - --auth
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_APP_USERNAME
      - MONGO_APP_PASSWORD

volumes:
  mongo_data:
    driver: local
  media_data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
