

services:
  payload:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - media_data:/app/media

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    command:
      - --storageEngine=wiredTiger
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: none

volumes:
  mongo_data:
  media_data:

networks:
  app-network:
    driver: bridge
