/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    homepage: Homepage;
    'sejarah-paroki': SejarahParoki;
    news: News;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'sejarah-paroki': SejarahParokiSelect<false> | SejarahParokiSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage homepage content including hero section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Internal title for this content (not displayed on frontend)
   */
  title: string;
  heroSection: {
    /**
     * The main hero title displayed on the homepage
     */
    title: string;
    /**
     * Hero background video (MP4 format recommended)
     */
    video: string | Media;
    /**
     * Alternative text for the video (for accessibility)
     */
    videoAlt?: string | null;
  };
  pengumumanSection: {
    /**
     * Section title for the announcements carousel
     */
    title: string;
    /**
     * Section subtitle/description
     */
    subtitle?: string | null;
    /**
     * Upload images for the pengumuman carousel
     */
    images?:
      | {
          /**
           * Title/name for this announcement image
           */
          title: string;
          /**
           * Upload the announcement image
           */
          image: string | Media;
          /**
           * Alternative text for accessibility
           */
          alt?: string | null;
          /**
           * Optional link when image is clicked
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage Sejarah Paroki (Parish History) page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sejarah-paroki".
 */
export interface SejarahParoki {
  id: string;
  /**
   * Page title for the Sejarah Paroki page
   */
  title: string;
  heroSection: {
    /**
     * Hero section title
     */
    title: string;
    /**
     * Hero section subtitle/description
     */
    subtitle?: string | null;
    /**
     * Hero background image (church/historical photo)
     */
    backgroundImage?: (string | null) | Media;
  };
  content?: {
    /**
     * Main article content about the parish history (optional - if not provided, timeline will be shown)
     */
    article?: string | null;
    /**
     * Featured image for the article
     */
    featuredImage?: (string | null) | Media;
    /**
     * Caption for the featured image
     */
    imageCaption?: string | null;
    quote?: {
      /**
       * Quote text
       */
      text?: string | null;
      /**
       * Quote author
       */
      author?: string | null;
    };
  };
  timeline?: {
    /**
     * Timeline introduction title (displays when no article content)
     */
    introTitle?: string | null;
    /**
     * Timeline introduction description (displays when no article content)
     */
    introDescription?: string | null;
    /**
     * Add timeline events with years, titles, and descriptions
     */
    events?:
      | {
          /**
           * Year of the event (e.g., "1979", "2017")
           */
          year: string;
          /**
           * Title of the timeline event
           */
          title: string;
          /**
           * Detailed description of the event (supports HTML)
           */
          content: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage news articles for the parish website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  /**
   * The title of the news article
   */
  title: string;
  /**
   * URL-friendly slug for the article (e.g., "perayaan-misa-natal-2024")
   */
  slug: string;
  /**
   * Short description/excerpt of the article (used in previews)
   */
  description: string;
  /**
   * Choose which Sapta Bidang this news belongs to
   */
  saptaBidang: 'pewartaan' | 'pelayanan' | 'persekutuan' | 'peribadatan' | 'pemerhati' | 'pitk' | 'okk';
  /**
   * Main image for the article (will be shown in previews and at the top of the article)
   */
  featuredImage: string | Media;
  /**
   * Main content of the article (supports rich text formatting and images)
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Name of the article author
   */
  author: string;
  /**
   * Date when the article was first published
   */
  publishedDate: string;
  /**
   * Estimated reading time in minutes (auto-calculated based on content length)
   */
  readingTime?: number | null;
  /**
   * Mark as featured article (will appear prominently on homepage)
   */
  featured?: boolean | null;
  /**
   * Publication status of the article
   */
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'homepage';
        value: string | Homepage;
      } | null)
    | ({
        relationTo: 'sejarah-paroki';
        value: string | SejarahParoki;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  title?: T;
  heroSection?:
    | T
    | {
        title?: T;
        video?: T;
        videoAlt?: T;
      };
  pengumumanSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        images?:
          | T
          | {
              title?: T;
              image?: T;
              alt?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sejarah-paroki_select".
 */
export interface SejarahParokiSelect<T extends boolean = true> {
  title?: T;
  heroSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  content?:
    | T
    | {
        article?: T;
        featuredImage?: T;
        imageCaption?: T;
        quote?:
          | T
          | {
              text?: T;
              author?: T;
            };
      };
  timeline?:
    | T
    | {
        introTitle?: T;
        introDescription?: T;
        events?:
          | T
          | {
              year?: T;
              title?: T;
              content?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  saptaBidang?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  publishedDate?: T;
  readingTime?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}