name: Code Quality & Testing

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      CI: true
      PAYLOAD_SECRET: test-secret
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      DATABASE_URI: mongodb://127.0.0.1:27017/test

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Wait for MongoDB
      run: |
        sudo apt-get update -y
        sudo apt-get install -y netcat-openbsd
        for i in {1..60}; do
          nc -z 127.0.0.1 27017 && echo "Mongo is up" && exit 0
          echo "Waiting for Mongo ($i) ..."; sleep 1
        done
        echo "Mongo did not start in time"; exit 1
        
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Type checking
      run: npm run generate:types && npx tsc --noEmit
      
    - name: Run integration tests
      run: npm run test:int

    - name: Run e2e tests
      env:
        NODE_OPTIONS: --no-deprecation
      run: npx playwright test --reporter=line
      
    - name: Build verification
      run: npm run build
      
    - name: Check bundle size
      run: npx @next/bundle-analyzer@latest build/static || echo "Bundle analyzer not available"
