name: Code Quality & Testing

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Type checking
      run: npm run type-check || npx tsc --noEmit
      
    - name: Run tests
      run: npm test
      
    - name: Build verification
      run: npm run build
      
    - name: Check bundle size
      run: npx @next/bundle-analyzer@latest build/static || echo "Bundle analyzer not available"
