name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security checks
      run: npm audit --audit-level=high
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -euo pipefail
          cd ${{ secrets.VPS_APP_DIR }}
          
          # Create production directory if it doesn't exist
          mkdir -p production
          cd production
          
          # If directory exists but is not a git repo, remove it
          if [ -d "santo-ambrosius" ] && [ ! -d "santo-ambrosius/.git" ]; then
            echo "Existing directory without git detected. Removing..."
            rm -rf santo-ambrosius
          fi
          
          # Clone or update production repository
          if [ ! -d "santo-ambrosius" ]; then
            echo "Cloning production repository..."
            git clone https://github.com/${{ github.repository }}.git santo-ambrosius
          fi
          
          cd santo-ambrosius
          
          # Ensure it's a git repo and sync to origin/main
          if [ ! -d ".git" ]; then
            echo "Directory exists but not a git repo. Recreating..."
            cd .. && rm -rf santo-ambrosius
            git clone https://github.com/${{ github.repository }}.git santo-ambrosius
            cd santo-ambrosius
          fi
          git fetch origin
          git reset --hard origin/main
          
          # Restore .env.production from parent if missing
          if [ ! -f ".env.production" ] && [ -f "../.env.production" ]; then
            echo "Copying ../.env.production into repo..."
            cp ../.env.production .env.production
          fi
          
          # Ensure production environment file exists
          if [ ! -f ".env.production" ]; then
            echo "ERROR: .env.production file not found at $(pwd)!"
            echo "Create it at $(pwd)/.env.production or at $(pwd)/../.env.production for auto-copy on next deploy."
            exit 1
          fi
          
          # Deploy with docker compose v2
          echo "Deploying to production with docker compose..."
          docker compose -f docker-compose.yml down || true
          docker compose -f docker-compose.yml up -d --build
          
          # Wait for services to be healthy
          echo "Waiting for services to be healthy..."
          sleep 30
          
          # Check container status
          docker compose -f docker-compose.yml ps
          
          echo "Production deployment completed successfully!"
          
    - name: Production Status
      run: |
        echo "🚀 Production deployment to ${{ secrets.VPS_HOST }} completed!"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Deployed at: $(date -u)"
